In [25]:
!pip install numpy

***Create a NumPy array***

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**0-array***

In [27]:
import numpy as np

arr = np.array(42)

print(arr)

42


**2-d array**

In [28]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


**3-d array**

In [29]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


***number of dimensions***

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimesions :',arr.ndmin)

[[[[[1 2 3 4]]]]]


AttributeError: 'numpy.ndarray' object has no attribute 'ndmin'

***arrange***

In [32]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


**Reshape**

In [33]:
arr = arr.reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Shape**

In [34]:
arr.shape

(3, 4)

**size**

In [35]:
arr.size

12